-- Run on PEYATST / shared Peya Oracle if T_* tables were created with CREATOR_ID / BUYER_ID columns.

ALTER TABLE T_EVENT RENAME COLUMN CREATOR_ID TO CREATOR_CODE_CLIENT;
ALTER TABLE T_TICKET RENAME COLUMN BUILT_BY_ID TO BUILT_BY_CODE_CLIENT;
ALTER TABLE T_TICKET RENAME COLUMN BUYER_ID TO BUYER_CODE_CLIENT;
ALTER TABLE T_TICKET RENAME COLUMN CONSUMED_BY_ID TO CONSUMED_BY_CODE_CLIENT;
ALTER TABLE T_ORDER RENAME COLUMN BUYER_ID TO BUYER_CODE_CLIENT;
ALTER TABLE T_TICKET_AUDIT_LOG RENAME COLUMN ACTOR_ID TO ACTOR_CODE_CLIENT;

COMMIT;
