-- Optional local Peya client stub (only when PEYA_API_ENABLED=false).
-- Safe to re-run: drops and recreates dev table.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TICKETING;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE W_CLIENTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE W_CLIENTS (
    CODE_CLIENT   VARCHAR2(50)  NOT NULL,
    EMAIL         VARCHAR2(200),
    GSMPRINCIPALE VARCHAR2(30),
    CODE_BANQUE   VARCHAR2(20),
    ACCOUND_ID    VARCHAR2(100),
    PASSWORD      VARCHAR2(200),
    DATECONNEXION TIMESTAMP,
    NOMCLIENT     VARCHAR2(200),
    ETAT          NUMBER(10),
    LOGINCLIENT   VARCHAR2(100),
    LOGIN         VARCHAR2(100),
    CONSTRAINT PK_W_CLIENTS PRIMARY KEY (CODE_CLIENT)
);

INSERT INTO W_CLIENTS (CODE_CLIENT, NOMCLIENT, GSMPRINCIPALE, EMAIL, ETAT)
VALUES ('DEV001', 'Dev Client', '0700000000', 'dev@example.com', 1);
COMMIT;
