-- Monpeya super-app auth schema (owned by MONPEYA user).
-- PeyaPay remains source of truth for wallet identity; we persist sessions + local profile cache.
-- Each init script is its own sqlplus session — always set container + schema here.

WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = MONPEYA;

CREATE SEQUENCE MP_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MP_DEVICE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MP_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MP_OTP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MP_USER (
    ID              NUMBER(19)      PRIMARY KEY,
    PHONE           VARCHAR2(20)    NOT NULL,
    CODE_CLIENT     VARCHAR2(50),
    NOM_CLIENT      VARCHAR2(200),
    EMAIL           VARCHAR2(200),
    ACCOUNT_ID      VARCHAR2(100),
    PEYA_STATUS     VARCHAR2(40),
    IS_PEYA_CLIENT  NUMBER(1)       DEFAULT 0 NOT NULL,
    IS_PEYAPAY_MERCHANT NUMBER(1)   DEFAULT 0 NOT NULL,
    IS_DEPLAFONNE   NUMBER(1)       DEFAULT 0 NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP,
    CONSTRAINT UK_MP_USER_PHONE UNIQUE (PHONE),
    CONSTRAINT CK_MP_USER_PEYA CHECK (IS_PEYA_CLIENT IN (0, 1)),
    CONSTRAINT CK_MP_USER_MERCHANT CHECK (IS_PEYAPAY_MERCHANT IN (0, 1)),
    CONSTRAINT CK_MP_USER_DEPLAF CHECK (IS_DEPLAFONNE IN (0, 1)),
    CONSTRAINT CK_MP_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'PENDING'))
);

CREATE INDEX IX_MP_USER_CODE_CLIENT ON MP_USER (CODE_CLIENT);

CREATE TABLE MP_DEVICE (
    ID              NUMBER(19)      PRIMARY KEY,
    USER_ID         NUMBER(19)      NOT NULL,
    IMEI            VARCHAR2(100),
    MODELE          VARCHAR2(200),
    PLATFORM        VARCHAR2(50),
    LAST_SEEN_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MP_DEVICE_USER FOREIGN KEY (USER_ID) REFERENCES MP_USER (ID)
);

CREATE INDEX IX_MP_DEVICE_USER ON MP_DEVICE (USER_ID);
CREATE INDEX IX_MP_DEVICE_IMEI ON MP_DEVICE (IMEI);

CREATE TABLE MP_SESSION (
    ID                  NUMBER(19)      PRIMARY KEY,
    USER_ID             NUMBER(19)      NOT NULL,
    DEVICE_ID           NUMBER(19),
    ACCESS_TOKEN        VARCHAR2(64)    NOT NULL,
    REFRESH_TOKEN       VARCHAR2(64)    NOT NULL,
    PEYA_ACCESS_TOKEN   VARCHAR2(4000),
    EXPIRES_AT          TIMESTAMP       NOT NULL,
    REFRESH_EXPIRES_AT  TIMESTAMP       NOT NULL,
    REVOKED             NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_MP_SESSION_ACCESS UNIQUE (ACCESS_TOKEN),
    CONSTRAINT UK_MP_SESSION_REFRESH UNIQUE (REFRESH_TOKEN),
    CONSTRAINT FK_MP_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES MP_USER (ID),
    CONSTRAINT FK_MP_SESSION_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES MP_DEVICE (ID),
    CONSTRAINT CK_MP_SESSION_REVOKED CHECK (REVOKED IN (0, 1))
);

CREATE INDEX IX_MP_SESSION_USER ON MP_SESSION (USER_ID);

-- OTP is issued by PeyaPay; we keep an audit trail for the super-app.
CREATE TABLE MP_OTP_CHALLENGE (
    ID              NUMBER(19)      PRIMARY KEY,
    PHONE           VARCHAR2(20)    NOT NULL,
    PURPOSE         VARCHAR2(40)    NOT NULL,
    STATUS          VARCHAR2(20)    NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERIFIED_AT     TIMESTAMP,
    CONSTRAINT CK_MP_OTP_PURPOSE CHECK (PURPOSE IN ('REGISTER', 'LOGIN', 'RESET_PIN')),
    CONSTRAINT CK_MP_OTP_STATUS CHECK (STATUS IN ('SENT', 'VERIFIED', 'FAILED'))
);

CREATE INDEX IX_MP_OTP_PHONE ON MP_OTP_CHALLENGE (PHONE);

COMMIT;
