-- Run all ticketing DDL as APP_USER (gvenzl/oracle-xe init scripts execute as SYS).
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TICKETING;
