-- Create immo schema user.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM dba_users WHERE username = 'IMMO';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER immo IDENTIFIED BY immo';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO immo';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO immo';
  END IF;
END;
/
