-- Mr Immo rental schema (rental-app API contract).
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = IMMO;

CREATE TABLE CODE_PAYS (
    ID          VARCHAR2(36) PRIMARY KEY,
    NOM         VARCHAR2(200) NOT NULL,
    CODE        VARCHAR2(10)  NOT NULL
);

CREATE TABLE TYPE_BIENS (
    ID          VARCHAR2(36) PRIMARY KEY,
    LIBELLE     VARCHAR2(200) NOT NULL,
    NOM         VARCHAR2(200)
);

CREATE TABLE BIENS (
    BIENS_ID           VARCHAR2(36) PRIMARY KEY,
    NOM                VARCHAR2(300) NOT NULL,
    DESCRIPTION        CLOB,
    PRIX               NUMBER(15,2),
    SUPERFICIE         NUMBER(10,2),
    ADRESSE            VARCHAR2(500),
    VILLE              VARCHAR2(200),
    CODE_POSTAL        VARCHAR2(20),
    LATITUDE           NUMBER(10,7),
    LONGITUDE          NUMBER(10,7),
    PHOTO              CLOB,
    COMMODITIES        CLOB,
    TYPE_BIENS_ID      VARCHAR2(36),
    STATUT             VARCHAR2(50) DEFAULT 'libre',
    CODE_PAYS_ID       VARCHAR2(36),
    UTILISATEURS_ID    VARCHAR2(50),
    DATE_CREATION      TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATE_ACQUISITION   DATE,
    EVALUATION_QUALITE NUMBER(4,2),
    CONSTRAINT FK_BIENS_TYPE FOREIGN KEY (TYPE_BIENS_ID) REFERENCES TYPE_BIENS(ID),
    CONSTRAINT FK_BIENS_PAYS FOREIGN KEY (CODE_PAYS_ID) REFERENCES CODE_PAYS(ID)
);

CREATE TABLE LOCATAIRES (
    LOCATAIRES_ID      VARCHAR2(36) PRIMARY KEY,
    NOM                VARCHAR2(200) NOT NULL,
    PRENOMS            VARCHAR2(200),
    EMAIL              VARCHAR2(200),
    TELEPHONE          VARCHAR2(50),
    CNI                VARCHAR2(100),
    ADRESSE            VARCHAR2(500),
    PROFESSION         VARCHAR2(200),
    REVENU_MENSUEL     NUMBER(15,2),
    DATE_NAISSANCE     TIMESTAMP,
    STATUT             VARCHAR2(50) DEFAULT 'actif',
    PHOTO              VARCHAR2(1000),
    BIENS_ID           VARCHAR2(36),
    UTILISATEURS_ID    VARCHAR2(50),
    MONTANT_LOYER      NUMBER(15,2),
    FREQUENCE_PAIEMENT VARCHAR2(50),
    DATE_DEBUT_BAIL    TIMESTAMP,
    DATE_FIN_BAIL      TIMESTAMP,
    JOUR_PAIEMENT      NUMBER(2),
    CONSTRAINT FK_LOC_BIENS FOREIGN KEY (BIENS_ID) REFERENCES BIENS(BIENS_ID)
);

CREATE TABLE PAIEMENTS (
    PAIEMENTS_ID          VARCHAR2(36) PRIMARY KEY,
    MONTANT               NUMBER(15,2) NOT NULL,
    DATE_PAIEMENT         TIMESTAMP,
    COMMENTAIRE           VARCHAR2(500),
    LOCATAIRES_ID         VARCHAR2(36),
    BIENS_ID              VARCHAR2(36),
    UTILISATEURS_ID       VARCHAR2(50),
    CONTRATS_LOCATION_ID  VARCHAR2(36),
    CONSTRAINT FK_PAY_LOC FOREIGN KEY (LOCATAIRES_ID) REFERENCES LOCATAIRES(LOCATAIRES_ID),
    CONSTRAINT FK_PAY_BIEN FOREIGN KEY (BIENS_ID) REFERENCES BIENS(BIENS_ID)
);

CREATE TABLE MESSAGES (
    MESSAGES_ID   VARCHAR2(36) PRIMARY KEY,
    SENDER_ID     VARCHAR2(50) NOT NULL,
    RECEIVER_ID   VARCHAR2(50) NOT NULL,
    CONTENT       CLOB NOT NULL,
    MESSAGE_TYPE  VARCHAR2(20) DEFAULT 'TEXT',
    SENT_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_READ       NUMBER(1) DEFAULT 0
);

INSERT INTO CODE_PAYS (ID, NOM, CODE) VALUES ('ci-default', 'Côte d''Ivoire', 'CI');

INSERT INTO TYPE_BIENS (ID, LIBELLE, NOM) VALUES ('0957a631-c7db-49e8-9517-22aea67a849e', 'Maison', 'house');
INSERT INTO TYPE_BIENS (ID, LIBELLE, NOM) VALUES ('004648d3-63ab-4405-b258-aa26e382d392', 'Immeuble', 'building');

COMMIT;
