-- Contrats de location + paiements récurrents (Mr Immo).
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = IMMO;

CREATE TABLE CONTRATS_LOCATION (
    CONTRATS_LOCATION_ID  VARCHAR2(36) PRIMARY KEY,
    BIENS_ID              VARCHAR2(36) NOT NULL,
    LOCATAIRES_ID         VARCHAR2(36) NOT NULL,
    UTILISATEURS_ID       VARCHAR2(50),
    MONTANT_LOYER         NUMBER(15,2),
    FREQUENCE_PAIEMENT    VARCHAR2(50) DEFAULT 'monthly',
    JOUR_PAIEMENT         NUMBER(2),
    DATE_DEBUT            TIMESTAMP,
    DATE_FIN              TIMESTAMP,
    STATUT                VARCHAR2(50) DEFAULT 'actif',
    DATE_CREATION         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CONTRAT_BIEN FOREIGN KEY (BIENS_ID) REFERENCES BIENS(BIENS_ID),
    CONSTRAINT FK_CONTRAT_LOC FOREIGN KEY (LOCATAIRES_ID) REFERENCES LOCATAIRES(LOCATAIRES_ID)
);

CREATE TABLE PAIEMENTS_RECURRENTS (
    PAIEMENTS_RECURRENTS_ID  VARCHAR2(36) PRIMARY KEY,
    CONTRATS_LOCATION_ID     VARCHAR2(36) NOT NULL,
    UTILISATEURS_ID          VARCHAR2(50),
    MONTANT                  NUMBER(15,2) NOT NULL,
    FREQUENCE                VARCHAR2(50) DEFAULT 'monthly',
    PROCHAIN_PAIEMENT        TIMESTAMP,
    DERNIER_PAIEMENT         TIMESTAMP,
    STATUT                   VARCHAR2(50) DEFAULT 'actif',
    DATE_CREATION            TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_REC_CONTRAT FOREIGN KEY (CONTRATS_LOCATION_ID) REFERENCES CONTRATS_LOCATION(CONTRATS_LOCATION_ID)
);

CREATE INDEX IX_CONTRAT_BIEN ON CONTRATS_LOCATION (BIENS_ID);
CREATE INDEX IX_CONTRAT_LOC ON CONTRATS_LOCATION (LOCATAIRES_ID);
CREATE INDEX IX_REC_CONTRAT ON PAIEMENTS_RECURRENTS (CONTRATS_LOCATION_ID);

COMMIT;
