name: app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter_contacts: ^1.1.9+2
  http: ^1.2.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.0
  webview_windows: ^0.4.0
  immo:
    path: ../packages/immo
  billetterie:
    path: ../packages/billetterie
  peyapay:
    path: ../packages/peyapay
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/logo/banks/
    - assets/logo/cards/
    - assets/modules/
    - ../packages/immo/assets/logo/immo/
