abstract final class BilletteriePrefs {
  static const onboardingSeen = '@billetterie_onboarding_seen';
  static const ticketPurpose = '@billetterie_ticket_purpose';
  static const ticketTypes = '@billetterie_ticket_types_v1';
  static const tickets = '@billetterie_tickets_v1';

  /// Ticket codes whose QR scratch foil has already been cleared.
  static const qrRevealedTicketIds = '@billetterie_qr_revealed_v1';

  /// Transport profile: client vs conductor + upgrade requests.
  static const transportProfile = '@billetterie_transport_profile_v1';
  static const notifications = '@billetterie_notifications_v1';

  /// Tickets generated by the conductor (business mode), keyed locally.
  static const conductorTickets = '@billetterie_conductor_tickets_v1';
}

enum TicketPurpose { buyer, organizer, scanner }
