/*
 * Created on 2020-02-26 ( Time 10:01:43 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.djogana.ticketing.api.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;

@Getter
@Setter
@Entity
@Table(name = "W_COMPTES")
public class WComptes {


	@JoinColumn(name = "CODE_CLIENT")
	@ManyToOne
	@JsonIgnore
	private WClients wClients;


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEOUVERTURE")
	private Date dateouverture;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEFERMTURE")
	private Date datefermture;

	@Column(name = "CODEEXPLVALIDATION", length = 15)
	private String codeexplvalidation;

	@Column(name = "CODEDEVISE", length = 5)
	private String codedevise;

	@Column(name = "SOLDEDISPO")
	private BigDecimal soldedispo;

	@Column(name = "SOLDECOMPTA")
	private BigDecimal soldecompta;

	@Column(name = "SOLDEAUTORISATION")
	private BigDecimal soldeautorisation;


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEDERNIERMVT")
	private Date datederniermvt;

	@Column(name = "CODE_BANQUE")
	private String codeBanque;



	@Column(name = "CODE_AGENCE")
	private String codeAgence;

	@Column(name = "CODE_SUR", length = 2)
	private String codeSur;

	@Id
	@Column(name = "NUMEROCOMPTECOMPLET", length = 25)
	private String numerocomptecomplet;

	@Column(name = "NGC", nullable = false, length = 6)
	private String ngc;

	@Column(name = "BLOQUAGE")
	private BigDecimal bloquage;

	@Column(name = "CODE_PACK", length = 25)
	private String codePack;

	@Column(name = "NCPTE_PARRAIN", length = 25)
	private String ncpteParrain;


	@Column(name = "NOMDUCOMPTE")
	private String nomDuCompte;


}
