/*
 * Created on 2020-02-29 ( Time 13:53:15 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.djogana.ticketing.api.entity;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Getter
@Setter
@Entity
@Table(name = "W_RETRAIT")
public class WRetrait {

	@Column(name = "CODEOPERATION", length = 3)
	private String codeoperation;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEOPERATION")
	private Date dateoperation;

	@Column(name = "HEURE_OPERATION")
	private Date heureOperation;

	@Column(name = "NUMERO_COMPTE", length = 50)
	private String numeroCompte;

	@Column(name = "CODE_BANQUE", length = 6)
	private String codeBanque;

	@Column(name = "CODE_AGENCE", length = 5)
	private String codeAgence;

	@Column(name = "LOGIN", length = 20)
	private String login;

	@Column(name = "CODE_CAISSE", length = 5)
	private String codeCaisse;

	@Column(name = "MONTANT")
	private BigDecimal montant;


	@Column(name = "COMPTE_COMMISSION", length = 50)
	private String compteCommission;

	@Column(name = "MONTANT_COMMISION")
	private Double montantCommision;


	@Column(name = "COMPTE_CREDIT", length = 50)
	private String compteCredit;

	@Column(name = "MONTANT_CREDIT")
	private BigDecimal montantCredit;

	@Column(name = "CODEOPERATIONBQ", length = 10)
	private String codeoperationbq;

	@Id
	@Column(name = "NUMRETRAIT", length = 16)
	private String numretrait;

	@Column(name = "COMPTE_TAXE", length = 50)
	private String compteTaxe;

	@Column(name = "MONTANT_TAXE")
	private BigDecimal montantTaxe;


	@Column(name = "RAP", length = 2)
	private String rap;

	@Column(name = "VRAP", length = 2)
	private String vrap;

	@Column(name = "X1", length = 10)
	private String x1;
}
