-- Ticketing platform schema (Oracle, UUID as VARCHAR2(36))
-- Run in DBeaver on TICKETING@XEPDB1 after 01-schema.sql (optional)

CREATE TABLE T_EVENT (
    ID                  VARCHAR2(36)    NOT NULL,
    EVENT_CODE          VARCHAR2(50)    NOT NULL,
    CREATOR_CODE_CLIENT VARCHAR2(50)    NOT NULL,
    CREATOR_NAME        VARCHAR2(200)   NOT NULL,
    CREATOR_PHONE       VARCHAR2(30),
    NAME                VARCHAR2(300)   NOT NULL,
    CATEGORY            VARCHAR2(50)    NOT NULL,
    VENUE_NAME          VARCHAR2(300),
    ADDRESS             VARCHAR2(500),
    CITY                VARCHAR2(100),
    COUNTRY             VARCHAR2(100),
    LATITUDE            NUMBER(10, 7),
    LONGITUDE           NUMBER(10, 7),
    START_AT            TIMESTAMP       NOT NULL,
    END_AT              TIMESTAMP       NOT NULL,
    TICKET_PRICE        NUMBER(18, 2)   NOT NULL,
    MAX_TICKETS         NUMBER(10)      NOT NULL,
    TICKETS_GENERATED   NUMBER(10)      DEFAULT 0 NOT NULL,
    TICKETS_SOLD        NUMBER(10)      DEFAULT 0 NOT NULL,
    TICKETS_CONSUMED    NUMBER(10)      DEFAULT 0 NOT NULL,
    STATUS              VARCHAR2(20)    NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PUBLISHED_AT        TIMESTAMP,
    CONSTRAINT PK_T_EVENT PRIMARY KEY (ID),
    CONSTRAINT UK_T_EVENT_CODE UNIQUE (EVENT_CODE),
    CONSTRAINT CK_T_EVENT_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE T_TICKET (
    ID                  VARCHAR2(36)    NOT NULL,
    TICKET_CODE         VARCHAR2(30)    NOT NULL,
    QR_PAYLOAD          VARCHAR2(500)   NOT NULL,
    PURPOSE             VARCHAR2(20)    DEFAULT 'EVENT' NOT NULL,
    EVENT_ID            VARCHAR2(36),
    EVENT_CODE          VARCHAR2(50),
    ORDER_ID            VARCHAR2(36),
    EVENT_NAME          VARCHAR2(300),
    EVENT_PLACE         VARCHAR2(500),
    EVENT_START_AT      TIMESTAMP,
    TICKET_TYPE         VARCHAR2(50)    DEFAULT 'STANDARD' NOT NULL,
    PRICE               NUMBER(18, 2)   NOT NULL,
    BUILT_BY_CODE_CLIENT VARCHAR2(50)   NOT NULL,
    BUILT_BY_NAME       VARCHAR2(200)   NOT NULL,
    GENERATED_AT        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    BUYER_CODE_CLIENT   VARCHAR2(50),
    BUYER_NAME          VARCHAR2(200),
    BUYER_PHONE         VARCHAR2(30),
    PURCHASED_AT        TIMESTAMP,
    AMOUNT_PAID         NUMBER(18, 2),
    PAYMENT_REFERENCE   VARCHAR2(100),
    REFER_OP            VARCHAR2(50),
    CONSUMED_AT         TIMESTAMP,
    CONSUMED_PLACE      VARCHAR2(300),
    CONSUMED_BY_CODE_CLIENT VARCHAR2(50),
    CONSUMED_BY_NAME    VARCHAR2(200),
    SCANNER_DEVICE_ID   VARCHAR2(100),
    STATUS              VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_T_TICKET PRIMARY KEY (ID),
    CONSTRAINT UK_T_TICKET_CODE UNIQUE (TICKET_CODE),
    CONSTRAINT FK_T_TICKET_EVENT FOREIGN KEY (EVENT_ID) REFERENCES T_EVENT (ID),
    CONSTRAINT CK_T_TICKET_STATUS CHECK (STATUS IN ('GENERATED', 'FOR_SALE', 'SOLD', 'CONSUMED', 'CANCELLED')),
    CONSTRAINT CK_T_TICKET_PURPOSE CHECK (PURPOSE IN ('EVENT', 'TRANSPORT', 'PASS', 'GENERIC'))
);

CREATE TABLE T_ORDER (
    ID                  VARCHAR2(36)    NOT NULL,
    ORDER_REF           VARCHAR2(50)    NOT NULL,
    EVENT_ID            VARCHAR2(36),
    TICKET_ID           VARCHAR2(36)    NOT NULL,
    BUYER_CODE_CLIENT   VARCHAR2(50)    NOT NULL,
    BUYER_NAME          VARCHAR2(200)   NOT NULL,
    BUYER_PHONE         VARCHAR2(30)    NOT NULL,
    CODE_CLIENT         VARCHAR2(50),
    AMOUNT              NUMBER(18, 2)   NOT NULL,
    PAYMENT_STATUS      VARCHAR2(20)    NOT NULL,
    PAYMENT_METHOD      VARCHAR2(30),
    PAYMENT_REFERENCE   VARCHAR2(100),
    REFER_OP            VARCHAR2(50),
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PAID_AT             TIMESTAMP,
    CONSTRAINT PK_T_ORDER PRIMARY KEY (ID),
    CONSTRAINT UK_T_ORDER_REF UNIQUE (ORDER_REF),
    CONSTRAINT FK_T_ORDER_EVENT FOREIGN KEY (EVENT_ID) REFERENCES T_EVENT (ID),
    CONSTRAINT FK_T_ORDER_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID),
    CONSTRAINT CK_T_ORDER_PAYMENT CHECK (PAYMENT_STATUS IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED'))
);

CREATE TABLE T_TICKET_AUDIT_LOG (
    ID                  VARCHAR2(36)    NOT NULL,
    TICKET_ID           VARCHAR2(36)    NOT NULL,
    ACTION              VARCHAR2(30)    NOT NULL,
    ACTOR_CODE_CLIENT   VARCHAR2(50),
    ACTOR_NAME          VARCHAR2(200),
    PLACE               VARCHAR2(300),
    METADATA_JSON       VARCHAR2(2000),
    OCCURRED_AT         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_T_TICKET_AUDIT PRIMARY KEY (ID),
    CONSTRAINT FK_T_AUDIT_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
);

CREATE INDEX IDX_T_EVENT_CREATOR ON T_EVENT (CREATOR_CODE_CLIENT);
CREATE INDEX IDX_T_EVENT_STATUS ON T_EVENT (STATUS);
CREATE INDEX IDX_T_TICKET_EVENT ON T_TICKET (EVENT_ID);
CREATE INDEX IDX_T_TICKET_EVENT_CODE ON T_TICKET (EVENT_CODE);
CREATE INDEX IDX_T_TICKET_STATUS ON T_TICKET (STATUS);
CREATE INDEX IDX_T_TICKET_BUYER ON T_TICKET (BUYER_CODE_CLIENT);
CREATE INDEX IDX_T_ORDER_EVENT ON T_ORDER (EVENT_ID);
CREATE INDEX IDX_T_AUDIT_TICKET ON T_TICKET_AUDIT_LOG (TICKET_ID);

COMMIT;
