-- Generic tickets (non-event) + code-based lookups. Safe to re-run on existing DB.

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TICKETING;

-- T_TICKET: optional event link, purpose, denormalized event code
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET ADD (PURPOSE VARCHAR2(20) DEFAULT ''EVENT'' NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET ADD (EVENT_CODE VARCHAR2(50))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET MODIFY (EVENT_ID NULL)';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET MODIFY (EVENT_NAME NULL)';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET MODIFY (EVENT_START_AT NULL)';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

UPDATE T_TICKET t
   SET t.EVENT_CODE = (SELECT e.EVENT_CODE FROM T_EVENT e WHERE e.ID = t.EVENT_ID)
 WHERE t.EVENT_ID IS NOT NULL AND t.EVENT_CODE IS NULL;

UPDATE T_TICKET SET PURPOSE = 'EVENT' WHERE PURPOSE IS NULL;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_ORDER MODIFY (EVENT_ID NULL)';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE T_TICKET ADD CONSTRAINT CK_T_TICKET_PURPOSE CHECK (PURPOSE IN (''EVENT'', ''TRANSPORT'', ''PASS'', ''GENERIC''))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2264 AND SQLCODE != -2261 THEN RAISE; END IF;
END;
/

CREATE INDEX IDX_T_TICKET_EVENT_CODE ON T_TICKET (EVENT_CODE);

COMMIT;
