-- Align existing DB with mock-payment model (no invented plan types).
-- Run as MONPEYA: sqlplus monpeya/monpeya@//localhost:1523/XEPDB1 @scripts/03-simplify-subscription-mock.sql

WHENEVER SQLERROR CONTINUE
SET DEFINE OFF

-- Drop seeded plan catalog (types not defined yet).
DELETE FROM MP_PLAN_FEATURE;
DELETE FROM MP_SUBSCRIPTION;
DELETE FROM MP_PLAN;

COMMIT;

WHENEVER SQLERROR EXIT SQL.SQLCODE

-- Make plan optional + mock payment columns.
ALTER TABLE MP_SUBSCRIPTION MODIFY (PLAN_ID NULL);

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD (PAYMENT_PROVIDER VARCHAR2(30) DEFAULT ''PEYAPAY'' NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD (PAYMENT_STATUS VARCHAR2(30) DEFAULT ''MOCK_PAID'' NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD (IS_MOCK_PAYMENT NUMBER(1) DEFAULT 1 NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION DROP CONSTRAINT CK_MP_SUB_PAY_STATUS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

ALTER TABLE MP_SUBSCRIPTION ADD CONSTRAINT CK_MP_SUB_PAY_STATUS
    CHECK (PAYMENT_STATUS IN ('PENDING', 'MOCK_PAID', 'PAID', 'FAILED'));

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION DROP CONSTRAINT CK_MP_SUB_MOCK';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

ALTER TABLE MP_SUBSCRIPTION ADD CONSTRAINT CK_MP_SUB_MOCK CHECK (IS_MOCK_PAYMENT IN (0, 1));

UPDATE MP_SERVICE_ACTION SET NAME = 'Souscrire (mock)' WHERE CODE = 'plan.subscribe';

COMMIT;
EXIT;
