-- Seed Billetterie single + grouped subscription plans (idempotent).
-- Run against MONPEYA schema (XEPDB1).

WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = MONPEYA;

-- Single: Billetterie only
MERGE INTO MP_PLAN t
USING (
  SELECT 'BILL_CLIENT_SINGLE' AS CODE,
         'Billetterie — Individuel' AS NAME,
         'Abonnement client pour la Billetterie uniquement (achat et mes billets).' AS DESCRIPTION,
         1000 AS PRICE,
         'XOF' AS CURRENCY,
         'MONTHLY' AS BILLING_PERIOD,
         0 AS TRIAL_DAYS,
         1 AS IS_DEFAULT,
         1 AS IS_ACTIVE
  FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  t.NAME = s.NAME,
  t.DESCRIPTION = s.DESCRIPTION,
  t.PRICE = s.PRICE,
  t.CURRENCY = s.CURRENCY,
  t.BILLING_PERIOD = s.BILLING_PERIOD,
  t.TRIAL_DAYS = s.TRIAL_DAYS,
  t.IS_DEFAULT = s.IS_DEFAULT,
  t.IS_ACTIVE = s.IS_ACTIVE,
  t.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  ID, CODE, NAME, DESCRIPTION, PRICE, CURRENCY, BILLING_PERIOD, TRIAL_DAYS, IS_DEFAULT, IS_ACTIVE, CREATED_AT, UPDATED_AT
) VALUES (
  MP_PLAN_SEQ.NEXTVAL, s.CODE, s.NAME, s.DESCRIPTION, s.PRICE, s.CURRENCY, s.BILLING_PERIOD, s.TRIAL_DAYS, s.IS_DEFAULT, s.IS_ACTIVE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Grouped: Billetterie + Immo (ready for later switch)
MERGE INTO MP_PLAN t
USING (
  SELECT 'BILL_CLIENT_GROUPED' AS CODE,
         'Billetterie + Immo — Groupé' AS NAME,
         'Abonnement groupé : Billetterie et services Immo (location / construction / collection).' AS DESCRIPTION,
         2500 AS PRICE,
         'XOF' AS CURRENCY,
         'MONTHLY' AS BILLING_PERIOD,
         0 AS TRIAL_DAYS,
         0 AS IS_DEFAULT,
         1 AS IS_ACTIVE
  FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  t.NAME = s.NAME,
  t.DESCRIPTION = s.DESCRIPTION,
  t.PRICE = s.PRICE,
  t.CURRENCY = s.CURRENCY,
  t.BILLING_PERIOD = s.BILLING_PERIOD,
  t.TRIAL_DAYS = s.TRIAL_DAYS,
  t.IS_DEFAULT = s.IS_DEFAULT,
  t.IS_ACTIVE = s.IS_ACTIVE,
  t.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  ID, CODE, NAME, DESCRIPTION, PRICE, CURRENCY, BILLING_PERIOD, TRIAL_DAYS, IS_DEFAULT, IS_ACTIVE, CREATED_AT, UPDATED_AT
) VALUES (
  MP_PLAN_SEQ.NEXTVAL, s.CODE, s.NAME, s.DESCRIPTION, s.PRICE, s.CURRENCY, s.BILLING_PERIOD, s.TRIAL_DAYS, s.IS_DEFAULT, s.IS_ACTIVE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Features for SINGLE
DELETE FROM MP_PLAN_FEATURE WHERE PLAN_ID IN (SELECT ID FROM MP_PLAN WHERE CODE = 'BILL_CLIENT_SINGLE');
INSERT INTO MP_PLAN_FEATURE (ID, PLAN_ID, MODULE_ID, SERVICE_ACTION_ID, FEATURE_CODE, DESCRIPTION)
SELECT MP_PLAN_FEATURE_SEQ.NEXTVAL, p.ID, m.ID, NULL, 'MODULE_ACCESS', 'Accès Billetterie client'
FROM MP_PLAN p
JOIN MP_MODULE m ON m.CODE = 'billetterie'
WHERE p.CODE = 'BILL_CLIENT_SINGLE';

-- Features for GROUPED
DELETE FROM MP_PLAN_FEATURE WHERE PLAN_ID IN (SELECT ID FROM MP_PLAN WHERE CODE = 'BILL_CLIENT_GROUPED');
INSERT INTO MP_PLAN_FEATURE (ID, PLAN_ID, MODULE_ID, SERVICE_ACTION_ID, FEATURE_CODE, DESCRIPTION)
SELECT MP_PLAN_FEATURE_SEQ.NEXTVAL, p.ID, m.ID, NULL, 'MODULE_ACCESS', 'Accès ' || m.NAME
FROM MP_PLAN p
CROSS JOIN MP_MODULE m
WHERE p.CODE = 'BILL_CLIENT_GROUPED'
  AND m.CODE IN ('billetterie', 'real-estate', 'construction', 'collection');

COMMIT;
