-- Enrich MP_USER from Peya wclients + create MP_ACCOUNT for datasCompte cache.
-- Safe to re-run on existing Oracle volume (WHENEVER SQLERROR CONTINUE for ADD columns).

WHENEVER SQLERROR CONTINUE
SET DEFINE OFF
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = MONPEYA;

ALTER TABLE MP_USER ADD ADRESSE VARCHAR2(500);
ALTER TABLE MP_USER ADD PROFESSION VARCHAR2(200);
ALTER TABLE MP_USER ADD LIEU_NAISSANCE VARCHAR2(200);
ALTER TABLE MP_USER ADD CODE_PAYS_RESIDENCE VARCHAR2(10);
ALTER TABLE MP_USER ADD LOGIN_CLIENT VARCHAR2(100);
ALTER TABLE MP_USER ADD CODE_BANQUE VARCHAR2(20);
ALTER TABLE MP_USER ADD NUMERO_COMPTE_COMPLET VARCHAR2(100);
ALTER TABLE MP_USER ADD SOLDE_DISPO NUMBER(19,2);

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE SEQUENCE MP_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MP_ACCOUNT (
    ID                      NUMBER(19)      PRIMARY KEY,
    USER_ID                 NUMBER(19)      NOT NULL,
    CODE_CLIENT             VARCHAR2(50),
    NUMERO_COMPTE_COMPLET   VARCHAR2(100),
    NOM_DU_COMPTE           VARCHAR2(200),
    CODE_BANQUE             VARCHAR2(20),
    CODE_AGENCE             VARCHAR2(20),
    TYPE_COMPTE             VARCHAR2(20),
    SOLDE_DISPO             NUMBER(19,2),
    SOLDE_COMPTA            NUMBER(19,2),
    IS_PRINCIPAL            NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MP_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES MP_USER (ID),
    CONSTRAINT CK_MP_ACCOUNT_PRINCIPAL CHECK (IS_PRINCIPAL IN (0, 1))
);

CREATE INDEX IX_MP_ACCOUNT_USER ON MP_ACCOUNT (USER_ID);
CREATE INDEX IX_MP_ACCOUNT_NUM ON MP_ACCOUNT (NUMERO_COMPTE_COMPLET);

EXIT;
