-- Per-service parameters as KEY / VALUE for mobile reuse.
-- Run: sqlplus monpeya/monpeya@//localhost:1521/XEPDB1 @08-module-params.sql
-- Then seed with: @08b-module-params-seed.sql

SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MP_MODULE_PARAM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MP_MODULE_PARAM (
            ID              NUMBER(19)      PRIMARY KEY,
            MODULE_ID       NUMBER(19)      NOT NULL,
            PARAM_KEY       VARCHAR2(80)    NOT NULL,
            PARAM_VALUE     VARCHAR2(1000),
            SORT_ORDER      NUMBER(5)       DEFAULT 0 NOT NULL,
            IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
            CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT UK_MP_MOD_PARAM UNIQUE (MODULE_ID, PARAM_KEY),
            CONSTRAINT FK_MP_MOD_PARAM_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MP_MODULE (ID),
            CONSTRAINT CK_MP_MOD_PARAM_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_MOD_PARAM_MODULE ON MP_MODULE_PARAM (MODULE_ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
EXIT;
