-- Dual role (CLIENT / BUSINESS) for product services except Leadway.
-- Everyone starts CLIENT; BUSINESS needs docs or PeyaPay merchant, then subscribe.
-- Run: sqlplus ... "@/tmp/09-service-roles-and-business.sql"

SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

-- ── Module role model ────────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_MODULE ADD (ROLE_MODEL VARCHAR2(30) DEFAULT ''CLIENT_AND_BUSINESS'' NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_MODULE ADD CONSTRAINT CK_MP_MODULE_ROLE_MODEL CHECK (ROLE_MODEL IN (''CLIENT_ONLY'', ''CLIENT_AND_BUSINESS''))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

UPDATE MP_MODULE SET ROLE_MODEL = 'CLIENT_ONLY'
WHERE CODE IN ('home', 'peyapay', 'leadway-assurance', 'subscriptions');

UPDATE MP_MODULE SET ROLE_MODEL = 'CLIENT_AND_BUSINESS'
WHERE CODE IN ('real-estate', 'construction', 'collection', 'billetterie');

-- ── Service action required role ─────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SERVICE_ACTION ADD (REQUIRED_ROLE VARCHAR2(20) DEFAULT ''ANY'' NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SERVICE_ACTION ADD CONSTRAINT CK_MP_ACTION_REQ_ROLE CHECK (REQUIRED_ROLE IN (''ANY'', ''CLIENT'', ''BUSINESS''))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

UPDATE MP_SERVICE_ACTION SET REQUIRED_ROLE = 'CLIENT'
WHERE CODE IN ('ticket.checkout', 'ticket.my', 'rental.contract');

UPDATE MP_SERVICE_ACTION SET REQUIRED_ROLE = 'BUSINESS'
WHERE CODE IN ('listing.create');

-- Business ticket actions (conductor / owner)
INSERT INTO MP_SERVICE_ACTION (ID, MODULE_ID, CODE, NAME, ACCESS_LEVEL, REQUIRED_ROLE)
SELECT MP_SERVICE_ACTION_SEQ.NEXTVAL, m.ID, a.CODE, a.NAME, 'SUBSCRIPTION', 'BUSINESS'
FROM MP_MODULE m
JOIN (
    SELECT 'ticket.issue' AS CODE, 'Emettre billet' AS NAME FROM DUAL UNION ALL
    SELECT 'ticket.validate', 'Valider billet' FROM DUAL
) a ON 1 = 1
WHERE m.CODE = 'billetterie'
  AND NOT EXISTS (
      SELECT 1 FROM MP_SERVICE_ACTION x
      WHERE x.MODULE_ID = m.ID AND x.CODE = a.CODE
  );

-- ── Subscription scoped by service + role ────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD (MODULE_ID NUMBER(19))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD (ROLE VARCHAR2(20) DEFAULT ''CLIENT'' NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD CONSTRAINT FK_MP_SUB_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MP_MODULE (ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SUBSCRIPTION ADD CONSTRAINT CK_MP_SUB_ROLE CHECK (ROLE IN (''CLIENT'', ''BUSINESS''))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_SUB_MODULE ON MP_SUBSCRIPTION (MODULE_ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── Per-user service profile (starts CLIENT) ────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MP_SERVICE_PROFILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MP_SERVICE_PROFILE (
            ID                      NUMBER(19)      PRIMARY KEY,
            USER_ID                 NUMBER(19)      NOT NULL,
            MODULE_ID               NUMBER(19)      NOT NULL,
            CURRENT_ROLE            VARCHAR2(20)    DEFAULT ''CLIENT'' NOT NULL,
            BUSINESS_STATUS         VARCHAR2(30)    DEFAULT ''NONE'' NOT NULL,
            UPGRADE_PATH            VARCHAR2(30),
            IS_PEYAPAY_MERCHANT     NUMBER(1)       DEFAULT 0 NOT NULL,
            NOTE                    VARCHAR2(500),
            CREATED_AT              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT              TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT UK_MP_SVC_PROFILE UNIQUE (USER_ID, MODULE_ID),
            CONSTRAINT FK_MP_SP_USER FOREIGN KEY (USER_ID) REFERENCES MP_USER (ID),
            CONSTRAINT FK_MP_SP_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MP_MODULE (ID),
            CONSTRAINT CK_MP_SP_ROLE CHECK (CURRENT_ROLE IN (''CLIENT'', ''BUSINESS'')),
            CONSTRAINT CK_MP_SP_BIZ_STATUS CHECK (BUSINESS_STATUS IN (''NONE'', ''PENDING_DOCS'', ''PENDING_REVIEW'', ''APPROVED'', ''REJECTED'')),
            CONSTRAINT CK_MP_SP_UPGRADE CHECK (UPGRADE_PATH IS NULL OR UPGRADE_PATH IN (''DOCUMENTS'', ''PEYAPAY_MERCHANT'')),
            CONSTRAINT CK_MP_SP_MERCHANT CHECK (IS_PEYAPAY_MERCHANT IN (0, 1))
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_SP_USER ON MP_SERVICE_PROFILE (USER_ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── Business upgrade documents ───────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MP_BUSINESS_DOC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MP_BUSINESS_DOCUMENT (
            ID                  NUMBER(19)      PRIMARY KEY,
            PROFILE_ID          NUMBER(19)      NOT NULL,
            DOC_TYPE            VARCHAR2(40)    NOT NULL,
            FILE_REF            VARCHAR2(500),
            STATUS              VARCHAR2(20)    DEFAULT ''PENDING'' NOT NULL,
            REVIEW_NOTE         VARCHAR2(500),
            CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT FK_MP_BD_PROFILE FOREIGN KEY (PROFILE_ID) REFERENCES MP_SERVICE_PROFILE (ID),
            CONSTRAINT CK_MP_BD_TYPE CHECK (DOC_TYPE IN (''ID_CARD_FRONT'', ''ID_CARD_BACK'', ''BUSINESS_REG'', ''OTHER'')),
            CONSTRAINT CK_MP_BD_STATUS CHECK (STATUS IN (''PENDING'', ''ACCEPTED'', ''REJECTED''))
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_BD_PROFILE ON MP_BUSINESS_DOCUMENT (PROFILE_ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Catalog params: roleModel for mobile
DELETE FROM MP_MODULE_PARAM WHERE PARAM_KEY = 'roleModel';

INSERT INTO MP_MODULE_PARAM (ID, MODULE_ID, PARAM_KEY, PARAM_VALUE, SORT_ORDER)
SELECT MP_MODULE_PARAM_SEQ.NEXTVAL, m.ID, 'roleModel', m.ROLE_MODEL, 5
FROM MP_MODULE m;

COMMIT;
EXIT;
