-- Cache Peya supplier/merchant flag (datasCompte.typcpt = S from rechercheclient).
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_USER ADD (IS_PEYAPAY_MERCHANT NUMBER(1) DEFAULT 0 NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_USER ADD CONSTRAINT CK_MP_USER_MERCHANT CHECK (IS_PEYAPAY_MERCHANT IN (0, 1))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

-- Backfill from cached supplier accounts.
UPDATE MP_USER u
SET IS_PEYAPAY_MERCHANT = 1
WHERE EXISTS (
    SELECT 1 FROM MP_ACCOUNT a
    WHERE a.USER_ID = u.ID
      AND UPPER(TRIM(a.TYPE_COMPTE)) = 'S'
);

COMMIT;
EXIT;
