-- Subscription / déplafonnement requests with approval workflow.
-- BUSINESS: debit at request → WAITING_FOR_APPROVAL | ON_REVIEW | APPROVED | REJECTED
-- CLIENT: must be déplafonné for straight debit; else DEPLAFONNEMENT request first.

SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_USER ADD (IS_DEPLAFONNE NUMBER(1) DEFAULT 0 NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_USER ADD CONSTRAINT CK_MP_USER_DEPLAF CHECK (IS_DEPLAFONNE IN (0, 1))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

-- Align service profile business statuses with approval workflow
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SERVICE_PROFILE DROP CONSTRAINT CK_MP_SP_BIZ_STATUS';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE MP_SERVICE_PROFILE ADD CONSTRAINT CK_MP_SP_BIZ_STATUS CHECK (
        BUSINESS_STATUS IN (
            ''NONE'', ''PENDING_DOCS'', ''PENDING_REVIEW'',
            ''WAITING_FOR_APPROVAL'', ''ON_REVIEW'', ''APPROVED'', ''REJECTED''
        ))';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE MP_SUB_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MP_SUBSCRIPTION_REQUEST (
            ID                  NUMBER(19)      PRIMARY KEY,
            USER_ID             NUMBER(19)      NOT NULL,
            MODULE_ID           NUMBER(19),
            PLAN_ID             NUMBER(19),
            ROLE                VARCHAR2(20)    DEFAULT ''CLIENT'' NOT NULL,
            REQUEST_TYPE        VARCHAR2(30)    NOT NULL,
            AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
            CURRENCY            VARCHAR2(3)     DEFAULT ''XOF'' NOT NULL,
            STATUS              VARCHAR2(30)    DEFAULT ''WAITING_FOR_APPROVAL'' NOT NULL,
            PAYMENT_PROVIDER    VARCHAR2(30)    DEFAULT ''PEYAPAY'' NOT NULL,
            PAYMENT_STATUS      VARCHAR2(30)    DEFAULT ''MOCK_PAID'' NOT NULL,
            PAYMENT_REF         VARCHAR2(100),
            IS_MOCK_PAYMENT     NUMBER(1)       DEFAULT 1 NOT NULL,
            DEBITED_AT          TIMESTAMP,
            REVIEWED_AT         TIMESTAMP,
            REVIEW_NOTE         VARCHAR2(500),
            SUBSCRIPTION_ID     NUMBER(19),
            CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT FK_MP_SR_USER FOREIGN KEY (USER_ID) REFERENCES MP_USER (ID),
            CONSTRAINT FK_MP_SR_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MP_MODULE (ID),
            CONSTRAINT FK_MP_SR_PLAN FOREIGN KEY (PLAN_ID) REFERENCES MP_PLAN (ID),
            CONSTRAINT FK_MP_SR_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES MP_SUBSCRIPTION (ID),
            CONSTRAINT CK_MP_SR_ROLE CHECK (ROLE IN (''CLIENT'', ''BUSINESS'')),
            CONSTRAINT CK_MP_SR_TYPE CHECK (REQUEST_TYPE IN (''BUSINESS_SUBSCRIBE'', ''DEPLAFONNEMENT'')),
            CONSTRAINT CK_MP_SR_STATUS CHECK (STATUS IN (
                ''WAITING_FOR_APPROVAL'', ''ON_REVIEW'', ''APPROVED'', ''REJECTED'')),
            CONSTRAINT CK_MP_SR_PAY CHECK (PAYMENT_STATUS IN (''PENDING'', ''MOCK_PAID'', ''PAID'', ''FAILED'', ''NONE'')),
            CONSTRAINT CK_MP_SR_MOCK CHECK (IS_MOCK_PAYMENT IN (0, 1))
        )';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_SR_USER ON MP_SUBSCRIPTION_REQUEST (USER_ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MP_SR_STATUS ON MP_SUBSCRIPTION_REQUEST (STATUS)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
EXIT;
