/// Common Côte d'Ivoire cities / Abidjan communes for transport tickets.
abstract final class TransportCities {
  static const List<String> all = [
    'Abidjan',
    'Cocody',
    'Plateau',
    'Marcory',
    'Treichville',
    'Yopougon',
    'Abobo',
    'Adjamé',
    'Koumassi',
    'Port-Bouët',
    'Bingerville',
    'Anyama',
    'Songon',
    'Grand-Bassam',
    'Bouaké',
    'Yamoussoukro',
    'San-Pédro',
    'Korhogo',
    'Daloa',
    'Man',
    'Gagnoa',
    'Divo',
    'Abengourou',
    'Bondoukou',
    'Odienné',
    'Séguéla',
    'Ferkessédougou',
    'Soubré',
    'Issia',
    'Agboville',
  ];
}
