import 'package:app/src/core/modules/app.module.dart';

class BundledModules {
  BundledModules._();

  static const catalog = [
    AppModule(
      id: 0,
      moduleKey: 'peyapay',
      name: 'Peya Pay',
      icon: 'wallet',
      url: 'native:peyapay',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 0,
    ),
    AppModule(
      id: 1,
      moduleKey: 'real-estate',
      name: 'Mr Immo Location',
      icon: 'immo-rental',
      url: 'native:immo/rental',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 1,
    ),
    AppModule(
      id: 2,
      moduleKey: 'construction',
      name: 'Mr Immo Construction',
      icon: 'immo-construction',
      url: 'native:immo/construction',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 2,
    ),
    AppModule(
      id: 3,
      moduleKey: 'collection',
      name: 'Mr Immo Collection',
      icon: 'immo-collection',
      url: 'native:immo/collection',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 3,
    ),
    AppModule(
      id: 6,
      moduleKey: 'leadway-assurance',
      name: 'Leadway Moto',
      icon: 'leadway',
      url: 'native:leadway',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 4,
    ),
    AppModule(
      id: 5,
      moduleKey: 'billetterie-transport',
      name: 'Billetterie Transport',
      icon: 'billetterie-transport',
      url: 'native:billetterie/transport',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 5,
    ),
    AppModule(
      id: 7,
      moduleKey: 'billetterie-event',
      name: 'Billetterie Événements',
      icon: 'billetterie-event',
      url: 'native:billetterie/event',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 6,
    ),
    AppModule(
      id: 8,
      moduleKey: 'mon-grenier',
      name: 'Mon Grenier',
      icon: 'grenier',
      url: 'native:grenier',
      type: ModuleLaunchType.native,
      source: ModuleSource.bundled,
      sortOrder: 7,
    ),
  ];
}
